spring.config.import=file:env.properties
spring.application.name=u5w19d4
# SERVER CONFIG
server.port=3001
# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/u5w19d3
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver=org.postgresql.Driver
spring.servlet.multipart.max-file-size=10MB
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
supersecret=${SUPERSECRET}
# CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}

